# Generated by Django 5.1.3 on 2024-11-22 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0002_inventoryitem_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Project',
        ),
    ]
