# Generated by Django 5.1.3 on 2024-11-26 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0003_alter_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitem',
            name='image',
            field=models.ImageField(blank=True, upload_to='uploads/inventory'),
        ),
        migrations.AlterField(
            model_name='pattern',
            name='image',
            field=models.ImageField(blank=True, upload_to='uploads/patterns'),
        ),
        migrations.AlterField(
            model_name='patternimage',
            name='image',
            field=models.ImageField(blank=True, upload_to='uploads/patterns'),
        ),
    ]
