# Generated by Django 5.1.3 on 2024-11-22 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0004_patternimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='pattern',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='patternimage',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
