# Generated by Django 5.1.3 on 2024-11-22 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0006_alter_inventoryitem_name_alter_pattern_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pattern',
            name='name',
            field=models.TextField(max_length=75),
        ),
        migrations.AlterField(
            model_name='profile',
            name='first',
            field=models.TextField(max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='last',
            field=models.TextField(max_length=50),
        ),
    ]
