# Generated by Django 5.1.3 on 2024-11-22 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0007_alter_pattern_name_alter_profile_first_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitem',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='pattern',
            name='name',
            field=models.CharField(max_length=75),
        ),
        migrations.AlterField(
            model_name='profile',
            name='first',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='last',
            field=models.CharField(max_length=50),
        ),
    ]
