# Generated by Django 5.1.3 on 2024-11-22 02:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0008_alter_inventoryitem_name_alter_pattern_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follower', to='project_app.profile')),
                ('following', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following', to='project_app.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('caption', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('pattern', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='project_app.pattern')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_app.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_app.profile')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_app.post')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_app.profile')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_app.post')),
            ],
        ),
        migrations.CreateModel(
            name='SavedPattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pattern', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_app.pattern')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_app.profile')),
            ],
        ),
        migrations.CreateModel(
            name='SavedPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_app.post')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_app.profile')),
            ],
        ),
    ]
