# Generated by Django 5.1.3 on 2024-12-06 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0008_alter_comment_id_alter_follow_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='pattern',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
