# Generated by Django 5.1.3 on 2024-11-22 02:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0009_follow_post_like_comment_savedpattern_savedpost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='pattern',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='project_app.pattern'),
        ),
    ]
