# Generated by Django 5.1.3 on 2024-12-08 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0010_delete_patternimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pattern',
            name='image',
            field=models.ImageField(upload_to='uploads/patterns'),
        ),
    ]
